apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort